### ISSUE TITLE
ALL "Latest Modlists" result in 404s

### ISSUE THREAD

**Issue by Freso** [Modwatch/Frontend#12]
I just tried to open every single modlist listed under "Latest Modlists" at https://modwat.ch/ and every single one resulted in a 404. One or two could have maybe been deleted. Maybe people get upset over something and massdeleted, but a 100% miss rate seems suspicious.

**Comment by ChrisHPZ** [comment]
Adding a comment here as I'm experiencing the same as Freso. Modwatch, if something is going on with your domain or you need hosting, let me know. I'd be happy to create a place for you on my domain.

**Comment by ansballard** [comment]
very weird, I'm just starting my day at work but I'll take a look soon as I get home. Weird that the latest list is loading but not the modlists themselves, not really sure what could be going on there yet. Thanks for the issue!

**Comment by ansballard** [comment]
There we go, looks like mlab (service that hosts my db) updated all instances to mongo 3.6. Which meant the library I use to make queries (mongoose) needed to be updated. https://github.com/Modwatch/API/pull/6 Updated those along with all the other outdated npm packages and got that deployed, seems to have fixed the issue. I'll close this but lemme know if you're still having issues.
