### ISSUE TITLE
Modwat.chi api server Not Responding

### ISSUE THREAD

**Issue by SheppsSon** [Modwatch/Frontend#15]
When I click upload I get an error saying Modwat.chi api server Not Responding I went into the API and got the message below.

![image](https://user-images.githubusercontent.com/46631691/71524463-5e8fb000-2893-11ea-904f-1c4810f26b29.png)

For further troubleshooting I went to the Modwat.ch site to see if anyone else had my chosen user name and they did not.

I then tried a few different usernames just to make sure.
If you need any other information please let me know.
Thank you

Pasted below are the instructions I used.

There are 3 text boxes: username, password, and file path. If you have never uploaded, the username and password can be whatever you want, as long as the username isn't already in use. The file path depends on your mod manager. If you're using Nexus Mod Manager, press the handy dandy "Using NMM" button. It will do all the magic for you. If using Mod Organizer, press the "Using MO" button. Then, find your MO install (wherever you extracted it), and go to profiles > your profile, and double click "plugins.txt". Finally, once you've done one of the two above things, press "Upload". It should upload, giving you some nice descriptive text in the console window to the side, and then you're free to share your mods with modwat.ch/u/username.

And for you daring devils, there is now a button for changing your password. Click it, type a new password, press submit, and you (should) have a brand new password.

**Comment by ansballard** [comment]
Yo! Sorry for the wait. So I think the issue here was that the database I've been running this on for ~6 years finally started filling up, and looks to be failing on random uploads. So I migrated the database last night and it seems to be running smoothly, so I'd try uploading again and see if it works. If not I'll see if there's anything specific to you, but I'm not seeing anything.

Happy holidays!

**Comment by SheppsSon** [comment]
Thanks that worked

Happy Holidays

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
